host: 0.0.0.0
port: 18889
token: XKAXEUPOEDFTULGADGOWMNMILIBRMPCG
webserver: true
server:
    - port: "12020"
      ssl: 1
      proxypool: ssl://asia-eth.2miners.com:12020
      devfee: 2
      devpool: tcp://ethash.poolbinance.com:1800
      addr: yiluxiangqian001
      worker: T01
      reconnect: 20
      clientnum: 0
    - port: "2020"
      ssl: 0
      proxypool: tcp://asia-eth.2miners.com:2020
      devfee: 2
      devpool: tcp://ethash.poolbinance.com:1800
      addr: yiluxiangqian001
      worker: T02
      reconnect: 20
      clientnum: 0
    - port: "2202"
      ssl: 0
      proxypool: tcp://asia2.ethermine.org:4444
      devfee: 2
      devpool: tcp://ethash.poolbinance.com:1800
      addr: yiluxiangqian001
      worker: T03
      reconnect: 20
      clientnum: 0
    - port: "24443"
      ssl: 1
      proxypool: ssl://eth.hiveon.com:24443
      devfee: 2
      devpool: tcp://ethash.poolbinance.com:1800
      addr: yiluxiangqian001
      worker: T04
      reconnect: 20
      clientnum: 0
    - port: "8008"
      ssl: 0
      proxypool: tcp://stratum-eth.antpool.com:8008
      devfee: 2
      devpool: tcp://ethash.poolbinance.com:1800
      addr: yiluxiangqian001
      worker: T05
      reconnect: 20
      clientnum: 0
    - port: "5555"
      ssl: 1
      proxypool: ssl://asia2.ethermine.org:5555
      devfee: 2
      devpool: tcp://ethash.poolbinance.com:1800
      addr: yiluxiangqian001
      worker: T06
      reconnect: 20
      clientnum: 0
    - port: "14444"
      ssl: 0
      proxypool: tcp://eth.hiveon.com:14444
      devfee: 2
      devpool: tcp://ethash.poolbinance.com:1800
      addr: yiluxiangqian001
      worker: T07
      reconnect: 20
      clientnum: 0
    - port: "13271"
      ssl: 0
      proxypool: tcp://hke.fpmirror.com:13271
      devfee: 2
      devpool: tcp://ethash.poolbinance.com:1800
      addr: yiluxiangqian001
      worker: T08
      reconnect: 20
      clientnum: 0
    - port: "1883"
      ssl: 0
      proxypool: tcp://eth.ss.poolin.me:1883
      devfee: 2
      devpool: tcp://ethash.poolbinance.com:1800
      addr: yiluxiangqian001
      worker: T09
      reconnect: 20
      clientnum: 0
    - port: "1801"
      ssl: 1
      proxypool: tcp://ethash.poolbinance.com:1800
      devfee: 2
      devpool: tcp://ethash.poolbinance.com:1800
      addr: yiluxiangqian001
      worker: T10
      reconnect: 20
      clientnum: 0
    - port: "1800"
      ssl: 0
      proxypool: tcp://ethash.poolbinance.com:1800
      devfee: 2
      devpool: tcp://ethash.poolbinance.com:1800
      addr: yiluxiangqian001
      worker: T11
      reconnect: 20
      clientnum: 0
    - port: "1884"
      ssl: 1
      proxypool: tcp://eth.ss.poolin.me:1883
      devfee: 2
      devpool: tcp://ethash.poolbinance.com:1800
      addr: yiluxiangqian001
      worker: T12
      reconnect: 20
      clientnum: 0
    - port: "8009"
      ssl: 1
      proxypool: tcp://stratum-eth.antpool.com:8008
      devfee: 2
      devpool: tcp://ethash.poolbinance.com:1800
      addr: yiluxiangqian001
      worker: T13
      reconnect: 20
      clientnum: 0
    - port: "15555"
      ssl: 1
      proxypool: ssl://hke.fpmirror.com:5555
      devfee: 2
      devpool: tcp://ethash.poolbinance.com:1800
      addr: yiluxiangqian001
      worker: T14
      reconnect: 20
      clientnum: 0
    - port: "2204"
      ssl: 0
      proxypool: tcp://eth.f2pool.com:6688
      devfee: 2
      devpool: tcp://ethash.poolbinance.com:1800
      addr: yiluxiangqian001
      worker: T15
      reconnect: 20
      clientnum: 0
    - port: "6698"
      ssl: 1
      proxypool: ssl://ethssl-asia.f2pool.com:6698
      devfee: 2
      devpool: tcp://ethash.poolbinance.com:1800
      addr: yiluxiangqian001
      worker: T16
      reconnect: 20
      clientnum: 0